version: '3.3'
services:
    # OpenTelemetry Collector
    otel_collector:
        image: otel/opentelemetry-collector-contrib:0.70.0
        command: --config=/etc/otel-collector-config.yaml
        volumes:
            - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
        ports:
            - "4318:4318" # OTLP over HTTP receiver
            - "9464:9464" # Prometheus exporter
        depends_on:
            - jaeger
            - prometheus
        networks:
            - pocketbase_observability_net

    # Jaeger
    jaeger:
        image: jaegertracing/all-in-one:1.41.0
        ports:
            - "14250:14250" # Collector gRPC
            - "16686:16686" # Web HTTP
        networks:
            - pocketbase_observability_net

    # Prometheus
    prometheus:
        image: prom/prometheus:v2.42.0
        command:
            - --config.file=/etc/prometheus/prometheus-config.yaml
            # - --feature-gates=pkg.translator.prometheus.NormalizeName
        volumes:
            - ./prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
        ports:
            - "9090:9090"
        networks:
            - pocketbase_observability_net

    # Grafana
    grafana:
        image: grafana/grafana-oss
        ports:
            - "3000:3000"
        volumes:
            - grafana-storage:/var/lib/grafana
        depends_on:
            - prometheus
        networks:
            - pocketbase_observability_net

networks:
    pocketbase_observability_net: 
volumes:
    grafana-storage:
            